# # C:\Users\NIKHIL\OneDrive\Desktop\logs\backend\prometheus\prometheus.yml
# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:
#   # ✅ Scrape FastAPI metrics
#   - job_name: 'fastapi'
#     metrics_path: /metrics
#     static_configs:
#       - targets: ['backend:8000']  # Correct service name from docker-compose.yml

#   # ✅ Scrape Prometheus internal metrics
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

#   # ✅ Scrape Loki metrics
#   - job_name: 'loki'
#     metrics_path: /metrics
#     static_configs:
#       - targets: ['loki:3100']

# # ✅ Optional: alerting rules (ensure the file exists and is mounted)
# rule_files:
#   - "alert.rules.yml"


global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  # ✅ FastAPI metrics
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']

  # ✅ Prometheus self-metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ✅ Loki metrics
  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']
