# C:\Users\NIKHIL\OneDrive\Desktop\logs\loki-config.yaml

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info   # Optional: Can be set to debug for troubleshooting

ingester:
  wal:
    dir: /loki/wal  # ✅ Ensure this path is writable in Docker volume
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_entries_limit_per_query: 5000     # Optional: prevent overload in heavy queries
  ingestion_rate_mb: 4                  # Optional: default is 4 MB/s per stream
  ingestion_burst_size_mb: 10           # Optional: allow burst ingestion
  max_streams_per_user: 5000            # Optional: useful for multi-source

chunk_store_config:
  max_look_back_period: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h   # 7 days

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: ""     # Optional: integrate with Alertmanager if needed
  ring:
    kvstore:
      store: inmemory
  enable_api: true
