global:
  scrape_interval: 15s  # How often to scrape metrics

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
